# Generated by Django 5.0.6 on 2024-06-16 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('level', models.IntegerField(default=0, editable=False)),
                ('debt', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='задолженность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('previous_network_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_link', to='network_links.networklink', verbose_name='предыдущее звено сети')),
            ],
            options={
                'verbose_name': 'звено сети',
                'verbose_name_plural': 'звенья сети',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('house_number', models.CharField(max_length=5, verbose_name='номер дома')),
                ('network_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='network_links.networklink', verbose_name='звено сети')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
        migrations.CreateModel(
            name='NetworkLinkProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='задолженность за продукт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('network_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_link_products', to='network_links.networklink', verbose_name='звено сети')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_link_products', to='products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'продукт звена сети',
                'verbose_name_plural': 'продукты звена сети',
            },
        ),
    ]
